### ISSUE TITLE
Update favicon.ico

### ISSUE THREAD

**Issue by caslabs** [manoa-fit-connect/manoa-fit-connect-app#41]
Please do work for this issue in a branch called issue-41

the current favicon.ico file is from the original project scaffold template. Please update the `favicon.ico` file that align with our Manoa Fit Connect brand icon

**Comment by BrandonTabios** [comment]
I added a new icon in this branch but am having trouble linking the icon correctly

**Comment by BrandonTabios** [comment]
got it working, had to clear my browser caches to see it.
